language: node_js
services:
  - mongodb
  - xvfb
  
sudo: false

addons:
  apt:
    sources:
      - mongodb-2.6-precise

    packages:
      - mongodb-org-server

cache:
  directories:
    - node_modules

# git:
#   depth: 5

node_js:
  - "8"
  - "10"
  - "12"

env:
    # Set TEST_FOLDER to avoid webgme dist build (not used here)
  - TEST_FOLDER=test

before_script:
  - export DISPLAY=:99.0

script:
  - "npm run build"
  - "npm test"
