
export const REQUEST_USER = 'REQUEST_USER';
export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const REQUEST_ORGANIZATIONS = 'REQUEST_ORGANIZATIONS';

export const REQUEST_USER_FAILURE = 'REQUEST_USER_FAILURE';
export const REQUEST_USERS_FAILURE = 'REQUEST_USERS_FAILURE';
export const REQUEST_PROJECTS_FAILURE = 'REQUEST_PROJECTS_FAILURE';
export const REQUEST_ORGANIZATIONS_FAILURE = 'REQUEST_ORGANIZATIONS_FAILURE';

export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_PROJECTS_SUCCESS = 'REQUEST_PROJECTS_SUCCESS';
export const REQUEST_ORGANIZATIONS_SUCCESS = 'REQUEST_ORGANIZATIONS_SUCCESS';

export const RECEIVE_USER = 'RECEIVE_USER';

function receiveUser(user) {
    return {
        type: RECEIVE_USER,
        user: user
    };
}
